PROC START_LOADER;
  PRG_STOP(PRODUCT_LOAD.STOP_LOADER);
  WAIT( !SL11 & !SL12 & !SL13);
  PRG_START(PRODUCT_LOAD.ON_LOADER);
  WAIT(SL12);
  PRG_START(PRODUCT_LOAD.OFF_LOADER);
  LOOP;
ENDPROC

PROC STOP_LOADER;
  PRG_STOP(PRODUCT_LOAD.START_LOADER);
  PRG_STOP(PRODUCT_LOAD.ON_LOADER);
  PRG_START(PRODUCT_LOAD.OFF_LOADER);
ENDPROC

PROC ON_LOADER;
  PRG_STOP(PRODUCT_LOAD.OFF_LOADER);
  ON(M11);
  WAIT(,TIMER_LOADER,TIME_15S);
  ON(M22);
  ON(M24);
  ON(M25);
  WAIT(,TIMER_LOADER,TIME_5M);
  PRG_START(PRODUCT_LOAD.OFF_LOADER);
  WAIT(,TIMER_LOADER,TIME_5M);
  LOOP;  
ENDPROC;

PROC OFF_LOADER;
  OFF(M22);
  OFF(M24);
  OFF(M25);
  OFF(M11);
ENDPROC;

PROC CHECK_LOADER1;
  WAIT(!SL21);
  MSG('0000','Low level vanadium');
  SET(ALERT_BEEP_COUNT,1);
  PRG_START(ALERT.BEEP);
  WAIT(!SL22);
  MSG('0000','Too low level vanadium');
  SET(ALERT_BEEP_COUNT,5);
  PRG_START(ALERT.BEEP);
  PRG_START(PRODUCT_LOAD.STOP_LOADER);
ENDPROC;

PROC CHECK_LOADER2;
  WAIT(!SL23);
  MSG('0000','Low level sulfur');
  SET(ALERT_BEEP_COUNT,1);
  PRG_START(ALERT.BEEP);
  WAIT(!SL22);
  MSG('0000','Too low level sulfur');
  SET(ALERT_BEEP_COUNT,5);
  PRG_START(ALERT.BEEP);
  PRG_START(PRODUCT_LOAD.STOP_LOADER);
ENDPROC;

PROC ON_M22_M24;
  ON(M24);
  ON(M22);
  WAIT(,TIMER_LOADER,TIME_5M);
  OFF(M24);
  OFF(M22);
ENDPROC;

PROC OFF_M22_M24;
  PRG_STOP(PRODUCT_LOAD.ON_M22_M24);
  OFF(M24);
  OFF(M22);
ENDPROC;

PROC ON_M24;
  ON(M24);
  WAIT(,TIMER_LOADER,TIME_5M);
  OFF(M24);
ENDPROC;

PROC OFF_M24;
  PRG_STOP(PRODUCT_LOAD.ON_M24);
  OFF(M24);
ENDPROC;

PROC ON_M25;
  ON(M25);
ENDPROC;

PROC OFF_M25;
  OFF(M25);
ENDPROC;

PROC ON_M11;
  ON(M11);
ENDPROC;

PROC OFF_M11;
  OFF(M11);
ENDPROC;